[package]
name = "p11"
version = "1.0.0"
authors = []

[addresses]

[dev-addresses]

[dependencies]
p14 = { local = "../p14" }
p15 = { local = "../p15" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core", subdir = "aptos-move/framework/move-stdlib", rev = "mainnet" }

[dev-dependencies]
